name: SOCI test
on:
  workflow_dispatch:
jobs:
  build:
    name: SOCI with containerd
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    env:
      SOCI_VERSION: "0.3.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install soci-snapshotter
        run: |
          wget --quiet https://github.com/awslabs/soci-snapshotter/releases/download/v$SOCI_VERSION/soci-snapshotter-$SOCI_VERSION-linux-amd64.tar.gz
          sudo tar -C /usr/local/bin -xvf soci-snapshotter-$SOCI_VERSION-linux-amd64.tar.gz soci soci-snapshotter-grpc

      - name: Check soci-snapshotter
        run: |
          sudo soci

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        env:
          AWS_REGION: ap-northeast-1
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_NAME }}:1
          outputs: type=oci,dest=/tmp/image.tar

      - name: Import image in containerd
        run: sudo ctr i import --base-name ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_NAME }} --digests --all-platforms /tmp/image.tar

      - name: Create soci index
        run: sudo soci create ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_NAME }}:1

      - name: Push image with containerd
        run: sudo ctr i push --user AWS:$(aws ecr get-login-password --region ap-northeast-1) ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_NAME }}:1

      - name: push SOCI index
        run: sudo soci push --user AWS:$(aws ecr get-login-password --region ap-northeast-1) ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_NAME }}:1
