name: SOCI test
on:
  workflow_dispatch:
jobs:
  version:
    name: SOCI check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install soci-snapshotter
        run: |
          wget https://github.com/awslabs/soci-snapshotter/releases/download/v0.3.0/soci-snapshotter-0.3.0-linux-amd64.tar.gz
          sudo tar -C /usr/local/bin -xvf soci-snapshotter-0.3.0-linux-amd64.tar.gz soci soci-snapshotter-grpc

      - name: Check soci-snapshotter
        run: |
          sudo soci
          sudo ctr

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Dcoker buildkit
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: ghcr.io/bateleurx/soci-test:latest
          push: true
